package se.wegelius.identityservice.model.HO;
// Generated Feb 17, 2017 7:42:39 PM by Hibernate Tools 4.3.1



/**
 * LoginsHO generated by hbm2java
 */
public class LoginsHO  implements java.io.Serializable {


     private Integer loginsId;
     private UsersHO users;
     private String passwordSalt;
     private String passwordHash;

    public LoginsHO() {
    }

    public LoginsHO(UsersHO users, String passwordSalt, String passwordHash) {
       this.users = users;
       this.passwordSalt = passwordSalt;
       this.passwordHash = passwordHash;
    }
   
    public Integer getLoginsId() {
        return this.loginsId;
    }
    
    public void setLoginsId(Integer loginsId) {
        this.loginsId = loginsId;
    }
    public UsersHO getUsers() {
        return this.users;
    }
    
    public void setUsers(UsersHO users) {
        this.users = users;
    }
    public String getPasswordSalt() {
        return this.passwordSalt;
    }
    
    public void setPasswordSalt(String passwordSalt) {
        this.passwordSalt = passwordSalt;
    }
    public String getPasswordHash() {
        return this.passwordHash;
    }
    
    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }




}


