package se.wegelius.identityservice.model.HO;
// Generated Feb 17, 2017 7:42:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UsersHO generated by hbm2java
 */
public class UsersHO  implements java.io.Serializable {


     private Integer usersId;
     private String firstName;
     private String lastName;
     private String email;
     private String mobile;
     private Set<LoginsHO> loginses = new HashSet<LoginsHO>(0);

    public UsersHO() {
    }

    public UsersHO(String firstName, String lastName, String email, String mobile, Set<LoginsHO> loginses) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.email = email;
       this.mobile = mobile;
       this.loginses = loginses;
    }
   
    public Integer getUsersId() {
        return this.usersId;
    }
    
    public void setUsersId(Integer usersId) {
        this.usersId = usersId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public Set<LoginsHO> getLoginses() {
        return this.loginses;
    }
    
    public void setLoginses(Set<LoginsHO> loginses) {
        this.loginses = loginses;
    }




}


