package se.wegelius.accessservice.model.ho;
// Generated Feb 20, 2017 9:49:45 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 *ClientHOt generated by hbm2java
 */
public class ClientHO  implements java.io.Serializable {


     private int clientId;
     private UserHO user;
     private String clientName;
     private String clientSecret;
     private String clientDescription;
     private String redirectUri;
     private String grantType;
     private Set<PermissionHO> permissions = new HashSet<PermissionHO>(0);

    public ClientHO() {
    }

	
    public ClientHO(int clientId) {
        this.clientId = clientId;
    }
    public ClientHO(int clientId, UserHO user, String clientName, String clientSecret, String clientDescription, String redirectUri, String grantType, Set<PermissionHO> permissions) {
       this.clientId = clientId;
       this.user = user;
       this.clientName = clientName;
       this.clientSecret = clientSecret;
       this.clientDescription = clientDescription;
       this.redirectUri = redirectUri;
       this.grantType = grantType;
       this.permissions = permissions;
    }

    public int getClientId() {
        return clientId;
    }

    public void setClientId(int clientId) {
        this.clientId = clientId;
    }

    public UserHO getUser() {
        return user;
    }

    public void setUser(UserHO user) {
        this.user = user;
    }

    public String getClientName() {
        return clientName;
    }

    public void setClientName(String clientName) {
        this.clientName = clientName;
    }

    public String getClientSecret() {
        return clientSecret;
    }

    public void setClientSecret(String clientSecret) {
        this.clientSecret = clientSecret;
    }

    public String getClientDescription() {
        return clientDescription;
    }

    public void setClientDescription(String clientDescription) {
        this.clientDescription = clientDescription;
    }

    public String getRedirectUri() {
        return redirectUri;
    }

    public void setRedirectUri(String redirectUri) {
        this.redirectUri = redirectUri;
    }

    public String getGrantType() {
        return grantType;
    }

    public void setGrantType(String grantType) {
        this.grantType = grantType;
    }

    public Set<PermissionHO> getPermissions() {
        return permissions;
    }

    public void setPermissions(Set<PermissionHO> permissions) {
        this.permissions = permissions;
    }
   
 
}


