package se.wegelius.accessservice.model.ho;
// Generated Feb 18, 2017 12:40:42 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 *ClientHOt generated by hbm2java
 */
public class ClientHO  implements java.io.Serializable {


     private int clientId;
     private UserHO user;
     private String clientName;
     private String clientDescription;
     private String redirectUri;
     private Set<PermissionHO> permissions = new HashSet<PermissionHO>(0);

    public ClientHO() {
    }

	
    public ClientHO(int clientId) {
        this.clientId = clientId;
    }
    public ClientHO(int clientId, UserHO user, String clientName, String clientDescription, String redirectUri, Set<PermissionHO> permissions) {
       this.clientId = clientId;
       this.user = user;
       this.clientName = clientName;
       this.clientDescription = clientDescription;
       this.redirectUri = redirectUri;
       this.permissions = permissions;
    }
   
    public int getClientId() {
        return this.clientId;
    }
    
    public void setClientId(int clientId) {
        this.clientId = clientId;
    }
    public UserHO getUser() {
        return this.user;
    }
    
    public void setUser(UserHO user) {
        this.user = user;
    }
    public String getClientName() {
        return this.clientName;
    }
    
    public void setClientName(String clientName) {
        this.clientName = clientName;
    }
    public String getClientDescription() {
        return this.clientDescription;
    }
    
    public void setClientDescription(String clientDescription) {
        this.clientDescription = clientDescription;
    }
    public String getRedirectUri() {
        return this.redirectUri;
    }
    
    public void setRedirectUri(String redirectUri) {
        this.redirectUri = redirectUri;
    }
    public Set<PermissionHO> getPermissions() {
        return this.permissions;
    }
    
    public void setPermissions(Set<PermissionHO> permissions) {
        this.permissions = permissions;
    }




}


