package se.wegelius.accessservice.model.ho;
// Generated Feb 20, 2017 9:49:45 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PermissionHO generated by hbm2java
 */
public class PermissionHO  implements java.io.Serializable {


     private Integer permissionId;
     private ClientHO client;
     private String object;
     private String target;
     private Set<RolePermissionHO> rolePermissions = new HashSet<RolePermissionHO>(0);

    public PermissionHO() {
    }

	
    public PermissionHO(ClientHO client) {
        this.client = client;
    }
    public PermissionHO(ClientHO client, String object, String target, Set<RolePermissionHO> rolePermissions) {
       this.client = client;
       this.object = object;
       this.target = target;
       this.rolePermissions = rolePermissions;
    }

    public Integer getPermissionId() {
        return permissionId;
    }

    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }

    public ClientHO getClient() {
        return client;
    }

    public void setClient(ClientHO client) {
        this.client = client;
    }

    public String getObject() {
        return object;
    }

    public void setObject(String object) {
        this.object = object;
    }

    public String getTarget() {
        return target;
    }

    public void setTarget(String target) {
        this.target = target;
    }

    public Set<RolePermissionHO> getRolePermissions() {
        return rolePermissions;
    }

    public void setRolePermissions(Set<RolePermissionHO> rolePermissions) {
        this.rolePermissions = rolePermissions;
    }
   
 
}


