package se.wegelius.accessservice.model.ho;
// Generated Feb 20, 2017 9:49:45 AM by Hibernate Tools 4.3.1



/**
 * RolePermissionHO generated by hbm2java
 */
public class RolePermissionHO  implements java.io.Serializable {


     private int rolePermissionId;
     private PermissionHO permission;
     private RoleHO role;

    public RolePermissionHO() {
    }

    public RolePermissionHO(int rolePermissionId, PermissionHO permission, RoleHO role) {
       this.rolePermissionId = rolePermissionId;
       this.permission = permission;
       this.role = role;
    }
   
    public int getRolePermissionId() {
        return this.rolePermissionId;
    }
    
    public void setRolePermissionId(int rolePermissionId) {
        this.rolePermissionId = rolePermissionId;
    }
    public PermissionHO getPermission() {
        return this.permission;
    }
    
    public void setPermission(PermissionHO permission) {
        this.permission = permission;
    }
    public RoleHO getRole() {
        return this.role;
    }
    
    public void setRole(RoleHO role) {
        this.role = role;
    }




}


