package se.wegelius.accessservice.model.ho;
// Generated Feb 20, 2017 9:49:45 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 *RoleHOe generated by hbm2java
 */
public class RoleHO  implements java.io.Serializable {


     private Integer roleId;
     private String roleName;
     private String roleDescription;
     private Set<RolePermissionHO> rolePermissions = new HashSet<RolePermissionHO>(0);
     private Set<UserRoleHO> userRoles = new HashSet<UserRoleHO>(0);

    public RoleHO() {
    }

	
    public RoleHO(String roleName) {
        this.roleName = roleName;
    }
    public RoleHO(String roleName, String roleDescription, Set<RolePermissionHO> rolePermissions, Set<UserRoleHO> userRoles) {
       this.roleName = roleName;
       this.roleDescription = roleDescription;
       this.rolePermissions = rolePermissions;
       this.userRoles = userRoles;
    }

    public Integer getRoleId() {
        return roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    public String getRoleDescription() {
        return roleDescription;
    }

    public void setRoleDescription(String roleDescription) {
        this.roleDescription = roleDescription;
    }

    public Set<RolePermissionHO> getRolePermissions() {
        return rolePermissions;
    }

    public void setRolePermissions(Set<RolePermissionHO> rolePermissions) {
        this.rolePermissions = rolePermissions;
    }

    public Set<UserRoleHO> getUserRoles() {
        return userRoles;
    }

    public void setUserRoles(Set<UserRoleHO> userRoles) {
        this.userRoles = userRoles;
    }
   
 
}


