package se.wegelius.accessservice.model.ho;
// Generated Feb 20, 2017 9:49:45 AM by Hibernate Tools 4.3.1



/**
 * UserRoleHO generated by hbm2java
 */
public class UserRoleHO  implements java.io.Serializable {


     private Integer userRoleId;
     private RoleHO role;
     private UserHO user;

    public UserRoleHO() {
    }

    public UserRoleHO(RoleHO role, UserHO user) {
       this.role = role;
       this.user = user;
    }
   
    public Integer getUserRoleId() {
        return this.userRoleId;
    }
    
    public void setUserRoleId(Integer userRoleId) {
        this.userRoleId = userRoleId;
    }
    public RoleHO getRole() {
        return this.role;
    }
    
    public void setRole(RoleHO role) {
        this.role = role;
    }
    public UserHO getUser() {
        return this.user;
    }
    
    public void setUser(UserHO user) {
        this.user = user;
    }




}


