package se.wegelius.speedvoter.voteservice.model.hibernateobjects;
// Generated Sep 16, 2016 5:00:33 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Elections generated by hbm2java
 */
public class ElectionsHO  implements java.io.Serializable {


     private Integer electionId;
     private EventsHO events;
     private String post;
     private Date date;
     private Integer minVotes;
     private Integer maxVotes;
     private Boolean secret;
     private Boolean active;
     private Set<VotesHO> voteses = new HashSet<>(0);
     private Set<OptionsHO> optionses = new HashSet<>(0);

    public ElectionsHO() {
    }

	
    public ElectionsHO(EventsHO events) {
        this.events = events;
    }
    public ElectionsHO(EventsHO events, String post, Date date, Integer minVotes, Integer maxVotes, Boolean secret, Boolean active, Set<VotesHO> voteses, Set<OptionsHO> optionses) {
       this.events = events;
       this.post = post;
       this.date = date;
       this.minVotes = minVotes;
       this.maxVotes = maxVotes;
       this.secret = secret;
       this.active = active;
       this.voteses = voteses;
       this.optionses = optionses;
    }
   
    public Integer getElectionId() {
        return this.electionId;
    }
    
    public void setElectionId(Integer electionId) {
        this.electionId = electionId;
    }
    public EventsHO getEvents() {
        return this.events;
    }
    
    public void setEvents(EventsHO events) {
        this.events = events;
    }
    public String getPost() {
        return this.post;
    }
    
    public void setPost(String post) {
        this.post = post;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Integer getMinVotes() {
        return this.minVotes;
    }
    
    public void setMinVotes(Integer minVotes) {
        this.minVotes = minVotes;
    }
    public Integer getMaxVotes() {
        return this.maxVotes;
    }
    
    public void setMaxVotes(Integer maxVotes) {
        this.maxVotes = maxVotes;
    }
    public Boolean getSecret() {
        return this.secret;
    }
    
    public void setSecret(Boolean secret) {
        this.secret = secret;
    }
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }
    public Set<VotesHO> getVoteses() {
        return this.voteses;
    }
    
    public void setVoteses(Set<VotesHO> voteses) {
        this.voteses = voteses;
    }
    public Set<OptionsHO> getOptionses() {
        return this.optionses;
    }
    
    public void setOptionses(Set<OptionsHO> optionses) {
        this.optionses = optionses;
    }




}


