package se.wegelius.speedvoter.voteservice.model.hibernateobjects;
// Generated Sep 16, 2016 5:00:33 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Events generated by hbm2java
 */
public class EventsHO  implements java.io.Serializable {


     private Integer eventId;
     private OrgsHO orgs;
     private String eventName;
     private Date startDate;
     private Date endDate;
     private Set<SpeakersHO> speakerses = new HashSet<SpeakersHO>(0);
     private Set<GateHO> gates = new HashSet<GateHO>(0);
     private Set<ElectionsHO> electionses = new HashSet<ElectionsHO>(0);

    public EventsHO() {
    }

    public EventsHO(OrgsHO orgs, String eventName, Date startDate, Date endDate, Set<SpeakersHO> speakerses, Set<GateHO> gates, Set<ElectionsHO> electionses) {
       this.orgs = orgs;
       this.eventName = eventName;
       this.startDate = startDate;
       this.endDate = endDate;
       this.speakerses = speakerses;
       this.gates = gates;
       this.electionses = electionses;
    }
   
    public Integer getEventId() {
        return this.eventId;
    }
    
    public void setEventId(Integer eventId) {
        this.eventId = eventId;
    }
    public OrgsHO getOrgs() {
        return this.orgs;
    }
    
    public void setOrgs(OrgsHO orgs) {
        this.orgs = orgs;
    }
    public String getEventName() {
        return this.eventName;
    }
    
    public void setEventName(String eventName) {
        this.eventName = eventName;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public Set<SpeakersHO> getSpeakerses() {
        return this.speakerses;
    }
    
    public void setSpeakerses(Set<SpeakersHO> speakerses) {
        this.speakerses = speakerses;
    }
    public Set<GateHO> getGates() {
        return this.gates;
    }
    
    public void setGates(Set<GateHO> gates) {
        this.gates = gates;
    }
    public Set<ElectionsHO> getElectionses() {
        return this.electionses;
    }
    
    public void setElectionses(Set<ElectionsHO> electionses) {
        this.electionses = electionses;
    }




}


