package se.wegelius.speedvoter.voteservice.model.hibernateobjects;
// Generated Sep 16, 2016 5:00:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Gate generated by hbm2java
 */
public class GateHO  implements java.io.Serializable {


     private Integer gateId;
     private EventsHO events;
     private VoterHO voter;
     private String accessCode;
     private Boolean active;
     private Set<SpeakersHO> speakerses = new HashSet<SpeakersHO>(0);
     private Set<VotersVotesHO> votersVoteses = new HashSet<VotersVotesHO>(0);

    public GateHO() {
    }

	
    public GateHO(EventsHO events, VoterHO voter) {
        this.events = events;
        this.voter = voter;
    }
    public GateHO(EventsHO events, VoterHO voter, String accessCode, Boolean active, Set<SpeakersHO> speakerses, Set<VotersVotesHO> votersVoteses) {
       this.events = events;
       this.voter = voter;
       this.accessCode = accessCode;
       this.active = active;
       this.speakerses = speakerses;
       this.votersVoteses = votersVoteses;
    }
   
    public Integer getGateId() {
        return this.gateId;
    }
    
    public void setGateId(Integer gateId) {
        this.gateId = gateId;
    }
    public EventsHO getEvents() {
        return this.events;
    }
    
    public void setEvents(EventsHO events) {
        this.events = events;
    }
    public VoterHO getVoter() {
        return this.voter;
    }
    
    public void setVoter(VoterHO voter) {
        this.voter = voter;
    }
    public String getAccessCode() {
        return this.accessCode;
    }
    
    public void setAccessCode(String accessCode) {
        this.accessCode = accessCode;
    }
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }
    public Set<SpeakersHO> getSpeakerses() {
        return this.speakerses;
    }
    
    public void setSpeakerses(Set<SpeakersHO> speakerses) {
        this.speakerses = speakerses;
    }
    public Set<VotersVotesHO> getVotersVoteses() {
        return this.votersVoteses;
    }
    
    public void setVotersVoteses(Set<VotersVotesHO> votersVoteses) {
        this.votersVoteses = votersVoteses;
    }




}


