package se.wegelius.speedvoter.voteservice.model.hibernateobjects;
// Generated Sep 16, 2016 5:00:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Options generated by hbm2java
 */
public class OptionsHO  implements java.io.Serializable {


     private Integer optionId;
     private ElectionsHO elections;
     private String theOption;
     private Set<VotesHO> voteses = new HashSet<VotesHO>(0);

    public OptionsHO() {
    }

	
    public OptionsHO(ElectionsHO elections) {
        this.elections = elections;
    }
    public OptionsHO(ElectionsHO elections, String theOption, Set<VotesHO> voteses) {
       this.elections = elections;
       this.theOption = theOption;
       this.voteses = voteses;
    }
   
    public Integer getOptionId() {
        return this.optionId;
    }
    
    public void setOptionId(Integer optionId) {
        this.optionId = optionId;
    }
    public ElectionsHO getElections() {
        return this.elections;
    }
    
    public void setElections(ElectionsHO elections) {
        this.elections = elections;
    }
    public String getTheOption() {
        return this.theOption;
    }
    
    public void setTheOption(String theOption) {
        this.theOption = theOption;
    }
    public Set<VotesHO> getVoteses() {
        return this.voteses;
    }
    
    public void setVoteses(Set<VotesHO> voteses) {
        this.voteses = voteses;
    }




}


