package se.wegelius.speedvoter.voteservice.model.hibernateobjects;
// Generated Sep 16, 2016 5:00:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Orgs generated by hbm2java
 */
public class OrgsHO  implements java.io.Serializable {


     private Integer orgId;
     private String orgname;
     private Set<VoterHO> voters = new HashSet<VoterHO>(0);
     private Set<EventsHO> eventses = new HashSet<EventsHO>(0);

    public OrgsHO() {
    }

    public OrgsHO(String orgname, Set<VoterHO> voters, Set<EventsHO> eventses) {
       this.orgname = orgname;
       this.voters = voters;
       this.eventses = eventses;
    }
   
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }
    public String getOrgname() {
        return this.orgname;
    }
    
    public void setOrgname(String orgname) {
        this.orgname = orgname;
    }
    public Set<VoterHO> getVoters() {
        return this.voters;
    }
    
    public void setVoters(Set<VoterHO> voters) {
        this.voters = voters;
    }
    public Set<EventsHO> getEventses() {
        return this.eventses;
    }
    
    public void setEventses(Set<EventsHO> eventses) {
        this.eventses = eventses;
    }




}


