package se.wegelius.speedvoter.voteservice.model.hibernateobjects;
// Generated Sep 16, 2016 5:00:33 PM by Hibernate Tools 4.3.1



/**
 * Series generated by hbm2java
 */
public class SeriesHO  implements java.io.Serializable {


     private Integer seriesId;
     private String accessCode;
     private String serie;
     private Boolean vacant;

    public SeriesHO() {
    }

    public SeriesHO(String accessCode, String serie, Boolean vacant) {
       this.accessCode = accessCode;
       this.serie = serie;
       this.vacant = vacant;
    }
   
    public Integer getSeriesId() {
        return this.seriesId;
    }
    
    public void setSeriesId(Integer seriesId) {
        this.seriesId = seriesId;
    }
    public String getAccessCode() {
        return this.accessCode;
    }
    
    public void setAccessCode(String accessCode) {
        this.accessCode = accessCode;
    }
    public String getSerie() {
        return this.serie;
    }
    
    public void setSerie(String serie) {
        this.serie = serie;
    }
    public Boolean getVacant() {
        return this.vacant;
    }
    
    public void setVacant(Boolean vacant) {
        this.vacant = vacant;
    }




}


