package se.wegelius.speedvoter.voteservice.model.hibernateobjects;
// Generated Sep 16, 2016 5:00:33 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Speakers generated by hbm2java
 */
public class SpeakersHO  implements java.io.Serializable {


     private Integer speakersId;
     private EventsHO events;
     private GateHO gate;
     private Date time;

    public SpeakersHO() {
    }

	
    public SpeakersHO(EventsHO events) {
        this.events = events;
    }
    public SpeakersHO(EventsHO events, GateHO gate, Date time) {
       this.events = events;
       this.gate = gate;
       this.time = time;
    }
   
    public Integer getSpeakersId() {
        return this.speakersId;
    }
    
    public void setSpeakersId(Integer speakersId) {
        this.speakersId = speakersId;
    }
    public EventsHO getEvents() {
        return this.events;
    }
    
    public void setEvents(EventsHO events) {
        this.events = events;
    }
    public GateHO getGate() {
        return this.gate;
    }
    
    public void setGate(GateHO gate) {
        this.gate = gate;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }




}


