package se.wegelius.speedvoter.voteservice.model.hibernateobjects;
// Generated Sep 16, 2016 5:00:33 PM by Hibernate Tools 4.3.1



/**
 * UsersUserrights generated by hbm2java
 */
public class UsersUserrightsHO  implements java.io.Serializable {


     private Integer usersUserrightsId;
     private UserrightsHO userrights;
     private UsersHO users;

    public UsersUserrightsHO() {
    }

    public UsersUserrightsHO(UserrightsHO userrights, UsersHO users) {
       this.userrights = userrights;
       this.users = users;
    }
   
    public Integer getUsersUserrightsId() {
        return this.usersUserrightsId;
    }
    
    public void setUsersUserrightsId(Integer usersUserrightsId) {
        this.usersUserrightsId = usersUserrightsId;
    }
    public UserrightsHO getUserrights() {
        return this.userrights;
    }
    
    public void setUserrights(UserrightsHO userrights) {
        this.userrights = userrights;
    }
    public UsersHO getUsers() {
        return this.users;
    }
    
    public void setUsers(UsersHO users) {
        this.users = users;
    }




}


