package se.wegelius.speedvoter.voteservice.model.hibernateobjects;
// Generated Sep 16, 2016 5:00:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class UsersHO  implements java.io.Serializable {


     private Integer userId;
     private String email;
     private String userpassword;
     private String name;
     private Set<UsersUserrightsHO> usersUserrightses = new HashSet<UsersUserrightsHO>(0);

    public UsersHO() {
    }

	
    public UsersHO(String email, String userpassword) {
        this.email = email;
        this.userpassword = userpassword;
    }
    public UsersHO(String email, String userpassword, String name, Set<UsersUserrightsHO> usersUserrightses) {
       this.email = email;
       this.userpassword = userpassword;
       this.name = name;
       this.usersUserrightses = usersUserrightses;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getUserpassword() {
        return this.userpassword;
    }
    
    public void setUserpassword(String userpassword) {
        this.userpassword = userpassword;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<UsersUserrightsHO> getUsersUserrightses() {
        return this.usersUserrightses;
    }
    
    public void setUsersUserrightses(Set<UsersUserrightsHO> usersUserrightses) {
        this.usersUserrightses = usersUserrightses;
    }




}


