package se.wegelius.speedvoter.voteservice.model.hibernateobjects;
// Generated Sep 16, 2016 5:00:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Userrights generated by hbm2java
 */
public class UserrightsHO  implements java.io.Serializable {


     private Integer userrightsId;
     private int level;
     private Integer org;
     private Boolean active;
     private Set<UsersUserrightsHO> usersUserrightses = new HashSet<UsersUserrightsHO>(0);

    public UserrightsHO() {
    }

	
    public UserrightsHO(int level) {
        this.level = level;
    }
    public UserrightsHO(int level, Integer org, Boolean active, Set<UsersUserrightsHO> usersUserrightses) {
       this.level = level;
       this.org = org;
       this.active = active;
       this.usersUserrightses = usersUserrightses;
    }
   
    public Integer getUserrightsId() {
        return this.userrightsId;
    }
    
    public void setUserrightsId(Integer userrightsId) {
        this.userrightsId = userrightsId;
    }
    public int getLevel() {
        return this.level;
    }
    
    public void setLevel(int level) {
        this.level = level;
    }
    public Integer getOrg() {
        return this.org;
    }
    
    public void setOrg(Integer org) {
        this.org = org;
    }
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }
    public Set<UsersUserrightsHO> getUsersUserrightses() {
        return this.usersUserrightses;
    }
    
    public void setUsersUserrightses(Set<UsersUserrightsHO> usersUserrightses) {
        this.usersUserrightses = usersUserrightses;
    }




}


