package se.wegelius.speedvoter.voteservice.model.hibernateobjects;
// Generated Sep 16, 2016 5:00:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Voter generated by hbm2java
 */
public class VoterHO  implements java.io.Serializable {


     private Integer voterId;
     private OrgsHO orgs;
     private String memberCode;
     private String name;
     private String mail;
     private String mobil;
     private Set<GateHO> gates = new HashSet<GateHO>(0);

    public VoterHO() {
    }

    public VoterHO(OrgsHO orgs, String memberCode, String name, String mail, String mobil, Set<GateHO> gates) {
       this.orgs = orgs;
       this.memberCode = memberCode;
       this.name = name;
       this.mail = mail;
       this.mobil = mobil;
       this.gates = gates;
    }
   
    public Integer getVoterId() {
        return this.voterId;
    }
    
    public void setVoterId(Integer voterId) {
        this.voterId = voterId;
    }
    public OrgsHO getOrgs() {
        return this.orgs;
    }
    
    public void setOrgs(OrgsHO orgs) {
        this.orgs = orgs;
    }
    public String getMemberCode() {
        return this.memberCode;
    }
    
    public void setMemberCode(String memberCode) {
        this.memberCode = memberCode;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public String getMobil() {
        return this.mobil;
    }
    
    public void setMobil(String mobil) {
        this.mobil = mobil;
    }
    public Set<GateHO> getGates() {
        return this.gates;
    }
    
    public void setGates(Set<GateHO> gates) {
        this.gates = gates;
    }




}


