package se.wegelius.speedvoter.voteservice.model.hibernateobjects;
// Generated Sep 16, 2016 5:00:33 PM by Hibernate Tools 4.3.1



/**
 * VotersVotes generated by hbm2java
 */
public class VotersVotesHO  implements java.io.Serializable {


     private Integer votersVoteId;
     private GateHO gate;
     private VotesHO votes;

    public VotersVotesHO() {
    }

    public VotersVotesHO(GateHO gate, VotesHO votes) {
       this.gate = gate;
       this.votes = votes;
    }
   
    public Integer getVotersVoteId() {
        return this.votersVoteId;
    }
    
    public void setVotersVoteId(Integer votersVoteId) {
        this.votersVoteId = votersVoteId;
    }
    public GateHO getGate() {
        return this.gate;
    }
    
    public void setGate(GateHO gate) {
        this.gate = gate;
    }
    public VotesHO getVotes() {
        return this.votes;
    }
    
    public void setVotes(VotesHO votes) {
        this.votes = votes;
    }




}


