package se.wegelius.speedvoter.voteservice.model.hibernateobjects;
// Generated Sep 16, 2016 5:00:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Votes generated by hbm2java
 */
public class VotesHO  implements java.io.Serializable {


     private Integer voteId;
     private ElectionsHO elections;
     private OptionsHO options;
     private Set<VotersVotesHO> votersVoteses = new HashSet<VotersVotesHO>(0);

    public VotesHO() {
    }

	
    public VotesHO(ElectionsHO elections, OptionsHO options) {
        this.elections = elections;
        this.options = options;
    }
    public VotesHO(ElectionsHO elections, OptionsHO options, Set<VotersVotesHO> votersVoteses) {
       this.elections = elections;
       this.options = options;
       this.votersVoteses = votersVoteses;
    }
   
    public Integer getVoteId() {
        return this.voteId;
    }
    
    public void setVoteId(Integer voteId) {
        this.voteId = voteId;
    }
    public ElectionsHO getElections() {
        return this.elections;
    }
    
    public void setElections(ElectionsHO elections) {
        this.elections = elections;
    }
    public OptionsHO getOptions() {
        return this.options;
    }
    
    public void setOptions(OptionsHO options) {
        this.options = options;
    }
    public Set<VotersVotesHO> getVotersVoteses() {
        return this.votersVoteses;
    }
    
    public void setVotersVoteses(Set<VotersVotesHO> votersVoteses) {
        this.votersVoteses = votersVoteses;
    }




}


